config/routes.rb
Rails.application.routes.draw do
  resources :registries
  resources :points
  resources :users
  resources :user_types
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: %i[ show edit update destroy ]

  # GET /points or /points.json
  def index
    @points = Point.all
  end

  # GET /points/1 or /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points or /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to point_url(@point), notice: "Point was successfully created." }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1 or /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to point_url(@point), notice: "Point was successfully updated." }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1 or /points/1.json
  def destroy
    @point.destroy

    respond_to do |format|
      format.html { redirect_to points_url, notice: "Point was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def point_params
      params.require(:point).permit(:amount, :user_id, :description)
    end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= form_with(model: point) do |form| %>
  <% if point.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
        <% point.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/points/_point.html.erb
<div id="<%= dom_id point %>">
  <p>
    <strong>Amount:</strong>
    <%= point.amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= point.user_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= point.description %>
  </p>

</div>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render "form", point: @point %>

<br>

<div>
  <%= link_to "Show this point", @point %> |
  <%= link_to "Back to points", points_path %>
</div>

app/views/points/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Points</h1>

<div id="points">
  <% @points.each do |point| %>
    <%= render point %>
    <p>
      <%= link_to "Show this point", point %>
    </p>
  <% end %>
</div>

<%= link_to "New point", new_point_path %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render "form", point: @point %>

<br>

<div>
  <%= link_to "Back to points", points_path %>
</div>

app/views/points/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @point %>

<div>
  <%= link_to "Edit this point", edit_point_path(@point) %> |
  <%= link_to "Back to points", points_path %>

  <%= button_to "Destroy this point", @point, method: :delete %>
</div>