config/routes.rb
Rails.application.routes.draw do
  resources :registries
  resources :points
  resources :users
  resources :user_types
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
  before_action :set_user_type, only: %i[ show edit update destroy ]

  # GET /user_types or /user_types.json
  def index
    @user_types = UserType.all
  end

  # GET /user_types/1 or /user_types/1.json
  def show
  end

  # GET /user_types/new
  def new
    @user_type = UserType.new
  end

  # GET /user_types/1/edit
  def edit
  end

  # POST /user_types or /user_types.json
  def create
    @user_type = UserType.new(user_type_params)

    respond_to do |format|
      if @user_type.save
        format.html { redirect_to user_type_url(@user_type), notice: "User type was successfully created." }
        format.json { render :show, status: :created, location: @user_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_types/1 or /user_types/1.json
  def update
    respond_to do |format|
      if @user_type.update(user_type_params)
        format.html { redirect_to user_type_url(@user_type), notice: "User type was successfully updated." }
        format.json { render :show, status: :ok, location: @user_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_types/1 or /user_types/1.json
  def destroy
    @user_type.destroy

    respond_to do |format|
      format.html { redirect_to user_types_url, notice: "User type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_type
      @user_type = UserType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_type_params
      params.require(:user_type).permit(:name)
    end
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/user_types/_form.html.erb
<%= form_with(model: user_type) do |form| %>
  <% if user_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_type.errors.count, "error") %> prohibited this user_type from being saved:</h2>

      <ul>
        <% user_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_types/_user_type.html.erb
<div id="<%= dom_id user_type %>">
  <p>
    <strong>Name:</strong>
    <%= user_type.name %>
  </p>

</div>

app/views/user_types/edit.html.erb
<h1>Editing user type</h1>

<%= render "form", user_type: @user_type %>

<br>

<div>
  <%= link_to "Show this user type", @user_type %> |
  <%= link_to "Back to user types", user_types_path %>
</div>

app/views/user_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User types</h1>

<div id="user_types">
  <% @user_types.each do |user_type| %>
    <%= render user_type %>
    <p>
      <%= link_to "Show this user type", user_type %>
    </p>
  <% end %>
</div>

<%= link_to "New user type", new_user_type_path %>

app/views/user_types/new.html.erb
<h1>New user type</h1>

<%= render "form", user_type: @user_type %>

<br>

<div>
  <%= link_to "Back to user types", user_types_path %>
</div>

app/views/user_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_type %>

<div>
  <%= link_to "Edit this user type", edit_user_type_path(@user_type) %> |
  <%= link_to "Back to user types", user_types_path %>

  <%= button_to "Destroy this user type", @user_type, method: :delete %>
</div>